; ==============================================================================
; PlatformIO Configuration: Laboratory Activity 3 - Edge AI Activity Tracker
; Target Hardware: RT-Thread Spark Board (STM32F407ZGT6)
; Host Testing: MinGW GCC Native Unity Suite
; ==============================================================================

[platformio]
default_envs = black_f407zg

[env:black_f407zg]
platform = ststm32
board = black_f407zg
framework = zephyr
upload_protocol = stlink
monitor_port = COM7
monitor_speed = 115200
build_flags =
    -Iinclude
    -O2
test_ignore = test_tinyml

; Static analysis configuration for project code
check_tool = cppcheck
check_skip_packages = yes
check_flags =
    cppcheck: --suppress=unusedFunction --inline-suppr

[env:native]
platform = native
test_framework = unity
test_build_src = yes
build_src_filter = -<*> +<feature_extractor.c>
build_flags =
    -Iinclude
    -O2
