/**
 * ==============================================================================
 * TinyML Activity Classifier Model (Kaggle run-or-walk)
 * Auto-generated by emlearn for ARM Cortex-M4F Hardware FPU
 * ==============================================================================
 * Target: STM32F407ZGT6 (RT-Thread Spark Board)
 * Input: 21 float features extracted from 15-sample (~2.8s) sliding window
 * Output: ACTIVITY_WALKING (0) or ACTIVITY_RUNNING (1)
 * Execution: Pure inline decision trees using single-precision FPU instructions
 * Memory: 0 dynamic allocations (0 malloc bytes)
 */

#ifndef TINYML_ACTIVITY_MODEL_H
#define TINYML_ACTIVITY_MODEL_H

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

#define ACTIVITY_NUM_FEATURES   21
#define ACTIVITY_NUM_TREES      10
#define ACTIVITY_WINDOW_SAMPLES 15

typedef enum {
    ACTIVITY_WALKING    = 0,
    ACTIVITY_RUNNING    = 1,
    ACTIVITY_STATIONARY = 2,
    ACTIVITY_UNKNOWN    = 255
} activity_type_t;

/* Minimum Dynamic Energy Thresholds using Standard Deviation (STD) */
#define MOTION_STD_THRESHOLD_MAG    0.075f  /* G-force STD of total magnitude (resting noise < 0.04g) */
#define MOTION_STD_THRESHOLD_AXES   0.150f  /* Sum of 3-axis acceleration STDs (std_ax + std_ay + std_az) */




    // !!! This file is generated using emlearn !!!

    #include <stdint.h>
    

static inline int32_t tinyml_activity_tree_0(const float *features, int32_t features_length) {
          if (features[6] < 0.230037f) {
              if (features[8] < 0.204904f) {
                  if (features[5] < 0.266033f) {
                      return 0;
                  } else {
                      if (features[7] < 0.526199f) {
                          return 0;
                      } else {
                          return 1;
                      }
                  }
              } else {
                  if (features[1] < -0.723103f) {
                      return 0;
                  } else {
                      return 1;
                  }
              }
          } else {
              if (features[13] < 0.892300f) {
                  if (features[1] < -0.016590f) {
                      return 0;
                  } else {
                      return 1;
                  }
              } else {
                  if (features[1] < -0.788143f) {
                      return 0;
                  } else {
                      if (features[19] < 0.148955f) {
                          return 0;
                      } else {
                          if (features[13] < 1.059500f) {
                              return 1;
                          } else {
                              return 1;
                          }
                      }
                  }
              }
          }
        }
        

static inline int32_t tinyml_activity_tree_1(const float *features, int32_t features_length) {
          if (features[1] < -0.788143f) {
              return 0;
          } else {
              if (features[7] < 0.274761f) {
                  if (features[7] < 0.262156f) {
                      if (features[3] < -0.295323f) {
                          return 0;
                      } else {
                          return 1;
                      }
                  } else {
                      return 0;
                  }
              } else {
                  if (features[10] < 0.348860f) {
                      return 0;
                  } else {
                      if (features[17] < 3.825350f) {
                          if (features[1] < -0.364913f) {
                              return 0;
                          } else {
                              return 1;
                          }
                      } else {
                          if (features[9] < 0.515088f) {
                              return 1;
                          } else {
                              return 1;
                          }
                      }
                  }
              }
          }
        }
        

static inline int32_t tinyml_activity_tree_2(const float *features, int32_t features_length) {
          if (features[8] < 0.168331f) {
              if (features[9] < 1.726217f) {
                  if (features[1] < -0.472760f) {
                      return 0;
                  } else {
                      return 1;
                  }
              } else {
                  if (features[0] < -0.188197f) {
                      return 1;
                  } else {
                      return 0;
                  }
              }
          } else {
              if (features[20] < 1.780804f) {
                  if (features[8] < 0.200160f) {
                      if (features[12] < 0.724200f) {
                          return 0;
                      } else {
                          if (features[7] < 0.393626f) {
                              return 0;
                          } else {
                              return 1;
                          }
                      }
                  } else {
                      if (features[6] < 0.176558f) {
                          if (features[11] < 2.769383f) {
                              return 0;
                          } else {
                              return 1;
                          }
                      } else {
                          if (features[11] < 1.566378f) {
                              return 1;
                          } else {
                              return 1;
                          }
                      }
                  }
              } else {
                  if (features[1] < -0.899863f) {
                      return 0;
                  } else {
                      return 1;
                  }
              }
          }
        }
        

static inline int32_t tinyml_activity_tree_3(const float *features, int32_t features_length) {
          if (features[1] < -0.802533f) {
              return 0;
          } else {
              if (features[17] < 2.281900f) {
                  if (features[2] < -0.709040f) {
                      return 0;
                  } else {
                      return 1;
                  }
              } else {
                  if (features[16] < 1.638250f) {
                      if (features[9] < 0.684623f) {
                          return 0;
                      } else {
                          return 1;
                      }
                  } else {
                      if (features[6] < 0.348083f) {
                          if (features[19] < 0.108234f) {
                              return 0;
                          } else {
                              return 1;
                          }
                      } else {
                          return 1;
                      }
                  }
              }
          }
        }
        

static inline int32_t tinyml_activity_tree_4(const float *features, int32_t features_length) {
          if (features[8] < 0.165210f) {
              if (features[9] < 1.705550f) {
                  if (features[2] < -0.049730f) {
                      if (features[1] < -0.479077f) {
                          return 0;
                      } else {
                          return 1;
                      }
                  } else {
                      if (features[6] < 0.274937f) {
                          return 0;
                      } else {
                          return 1;
                      }
                  }
              } else {
                  if (features[17] < 5.529700f) {
                      if (features[6] < 0.257406f) {
                          return 0;
                      } else {
                          return 1;
                      }
                  } else {
                      if (features[12] < 0.910100f) {
                          return 0;
                      } else {
                          return 1;
                      }
                  }
              }
          } else {
              if (features[6] < 0.196142f) {
                  if (features[8] < 0.263589f) {
                      if (features[2] < -0.461753f) {
                          return 1;
                      } else {
                          return 0;
                      }
                  } else {
                      return 1;
                  }
              } else {
                  if (features[10] < 0.410314f) {
                      return 0;
                  } else {
                      if (features[20] < 1.575847f) {
                          if (features[7] < 0.364603f) {
                              return 0;
                          } else {
                              return 1;
                          }
                      } else {
                          if (features[20] < 1.706322f) {
                              return 1;
                          } else {
                              return 1;
                          }
                      }
                  }
              }
          }
        }
        

static inline int32_t tinyml_activity_tree_5(const float *features, int32_t features_length) {
          if (features[7] < 0.367607f) {
              if (features[14] < 0.661600f) {
                  if (features[0] < -0.697970f) {
                      return 1;
                  } else {
                      if (features[0] < -0.528123f) {
                          if (features[1] < -0.507553f) {
                              return 0;
                          } else {
                              return 1;
                          }
                      } else {
                          return 0;
                      }
                  }
              } else {
                  if (features[14] < 0.831650f) {
                      if (features[0] < -0.597630f) {
                          return 1;
                      } else {
                          if (features[17] < 1.942250f) {
                              return 1;
                          } else {
                              return 0;
                          }
                      }
                  } else {
                      if (features[6] < 0.208284f) {
                          return 0;
                      } else {
                          return 1;
                      }
                  }
              }
          } else {
              if (features[1] < -0.802533f) {
                  return 0;
              } else {
                  if (features[11] < 0.514883f) {
                      return 0;
                  } else {
                      if (features[5] < 0.607503f) {
                          if (features[15] < 1.916350f) {
                              return 1;
                          } else {
                              return 1;
                          }
                      } else {
                          if (features[12] < 1.501950f) {
                              return 0;
                          } else {
                              return 1;
                          }
                      }
                  }
              }
          }
        }
        

static inline int32_t tinyml_activity_tree_6(const float *features, int32_t features_length) {
          if (features[19] < 0.370451f) {
              if (features[1] < -0.484860f) {
                  if (features[14] < 0.941550f) {
                      return 0;
                  } else {
                      if (features[4] < -0.203467f) {
                          return 1;
                      } else {
                          return 0;
                      }
                  }
              } else {
                  return 1;
              }
          } else {
              if (features[1] < -0.856497f) {
                  return 0;
              } else {
                  return 1;
              }
          }
        }
        

static inline int32_t tinyml_activity_tree_7(const float *features, int32_t features_length) {
          if (features[12] < 0.764400f) {
              if (features[2] < -0.370573f) {
                  if (features[7] < 0.381581f) {
                      return 0;
                  } else {
                      return 1;
                  }
              } else {
                  return 0;
              }
          } else {
              if (features[8] < 0.122127f) {
                  if (features[6] < 0.352783f) {
                      if (features[9] < 1.498725f) {
                          if (features[3] < 0.215833f) {
                              return 0;
                          } else {
                              return 1;
                          }
                      } else {
                          if (features[0] < -0.066210f) {
                              return 1;
                          } else {
                              return 0;
                          }
                      }
                  } else {
                      return 1;
                  }
              } else {
                  if (features[1] < -0.815307f) {
                      return 0;
                  } else {
                      if (features[19] < 0.115289f) {
                          return 0;
                      } else {
                          if (features[3] < -0.428667f) {
                              return 1;
                          } else {
                              return 1;
                          }
                      }
                  }
              }
          }
        }
        

static inline int32_t tinyml_activity_tree_8(const float *features, int32_t features_length) {
          if (features[13] < 1.171100f) {
              if (features[6] < 0.378060f) {
                  if (features[2] < -0.469553f) {
                      if (features[6] < 0.269606f) {
                          return 1;
                      } else {
                          return 0;
                      }
                  } else {
                      return 0;
                  }
              } else {
                  if (features[1] < -0.686597f) {
                      return 0;
                  } else {
                      return 1;
                  }
              }
          } else {
              if (features[20] < 1.960658f) {
                  if (features[6] < 0.191426f) {
                      if (features[0] < 0.443983f) {
                          return 0;
                      } else {
                          return 1;
                      }
                  } else {
                      if (features[1] < -0.484860f) {
                          return 0;
                      } else {
                          return 1;
                      }
                  }
              } else {
                  if (features[12] < 0.855500f) {
                      if (features[6] < 0.205318f) {
                          return 0;
                      } else {
                          if (features[18] < 1.107830f) {
                              return 1;
                          } else {
                              return 0;
                          }
                      }
                  } else {
                      return 1;
                  }
              }
          }
        }
        

static inline int32_t tinyml_activity_tree_9(const float *features, int32_t features_length) {
          if (features[17] < 5.656500f) {
              if (features[8] < 0.162851f) {
                  if (features[0] < -0.547780f) {
                      return 1;
                  } else {
                      return 0;
                  }
              } else {
                  if (features[6] < 0.293439f) {
                      if (features[1] < -0.716370f) {
                          return 0;
                      } else {
                          if (features[5] < -0.086900f) {
                              return 1;
                          } else {
                              return 0;
                          }
                      }
                  } else {
                      if (features[18] < 1.039357f) {
                          if (features[8] < 0.338502f) {
                              return 1;
                          } else {
                              return 1;
                          }
                      } else {
                          return 1;
                      }
                  }
              }
          } else {
              if (features[7] < 0.371483f) {
                  if (features[12] < 1.312400f) {
                      return 0;
                  } else {
                      if (features[20] < 1.688358f) {
                          if (features[20] < 1.417341f) {
                              return 1;
                          } else {
                              return 0;
                          }
                      } else {
                          return 1;
                      }
                  }
              } else {
                  if (features[7] < 0.432097f) {
                      if (features[14] < 0.507800f) {
                          if (features[0] < -0.600837f) {
                              return 1;
                          } else {
                              return 0;
                          }
                      } else {
                          if (features[17] < 10.251850f) {
                              return 1;
                          } else {
                              return 0;
                          }
                      }
                  } else {
                      return 1;
                  }
              }
          }
        }
        

static inline int32_t tinyml_activity_predict(const float *features, int32_t features_length) {

        int32_t votes[2] = {0,};
        int32_t _class = -1;

        _class = tinyml_activity_tree_0(features, features_length); votes[_class] += 1;
    _class = tinyml_activity_tree_1(features, features_length); votes[_class] += 1;
    _class = tinyml_activity_tree_2(features, features_length); votes[_class] += 1;
    _class = tinyml_activity_tree_3(features, features_length); votes[_class] += 1;
    _class = tinyml_activity_tree_4(features, features_length); votes[_class] += 1;
    _class = tinyml_activity_tree_5(features, features_length); votes[_class] += 1;
    _class = tinyml_activity_tree_6(features, features_length); votes[_class] += 1;
    _class = tinyml_activity_tree_7(features, features_length); votes[_class] += 1;
    _class = tinyml_activity_tree_8(features, features_length); votes[_class] += 1;
    _class = tinyml_activity_tree_9(features, features_length); votes[_class] += 1;
    
        int32_t most_voted_class = -1;
        int32_t most_voted_votes = 0;
        for (int32_t i=0; i<2; i++) {

            if (votes[i] > most_voted_votes) {
                most_voted_class = i;
                most_voted_votes = votes[i];
            }
        }
        return most_voted_class;
    }
    

static inline int tinyml_activity_predict_proba(const float *features, int32_t features_length, float *out, int out_length) {

        int32_t _class = -1;

        for (int i=0; i<out_length; i++) {
            out[i] = 0.0f;
        }

        _class = tinyml_activity_tree_0(features, features_length); out[_class] += 1.0f;
    _class = tinyml_activity_tree_1(features, features_length); out[_class] += 1.0f;
    _class = tinyml_activity_tree_2(features, features_length); out[_class] += 1.0f;
    _class = tinyml_activity_tree_3(features, features_length); out[_class] += 1.0f;
    _class = tinyml_activity_tree_4(features, features_length); out[_class] += 1.0f;
    _class = tinyml_activity_tree_5(features, features_length); out[_class] += 1.0f;
    _class = tinyml_activity_tree_6(features, features_length); out[_class] += 1.0f;
    _class = tinyml_activity_tree_7(features, features_length); out[_class] += 1.0f;
    _class = tinyml_activity_tree_8(features, features_length); out[_class] += 1.0f;
    _class = tinyml_activity_tree_9(features, features_length); out[_class] += 1.0f;
    
        // compute mean
        for (int i=0; i<out_length; i++) {
            out[i] = out[i] / 10;
        }
        return 0;
    }
    

/**
 * @brief Predicts human movement activity from 21 extracted time-domain features.
 *        First checks dynamic movement energy via acceleration Standard Deviation (STD)
 *        to identify stationary/resting conditions, then evaluates the 10-Tree Random
 *        Forest classifier on the ARM Cortex-M4F hardware FPU for active movement.
 * 
 * @param features Pointer to array of 21 float features:
 *                 [0..5]:   Means (ax, ay, az, gx, gy, gz)
 *                 [6..11]:  Std Devs (ax, ay, az, gx, gy, gz)
 *                 [12..17]: Ranges (ax, ay, az, gx, gy, gz)
 *                 [18..20]: Total Accel Magnitude (mean, std, max)
 * @param out_confidence Output pointer for classification confidence (0 to 100 percent)
 * @return activity_type_t ACTIVITY_STATIONARY, ACTIVITY_WALKING, or ACTIVITY_RUNNING
 */
static inline activity_type_t tinyml_predict_activity(const float *features, uint8_t *out_confidence)
{
    float mag_std = features[19];
    float sum_std = features[6] + features[7] + features[8];

    /* Dynamic motion gating using Standard Deviation (STD):
     * If the sensor variance is below human movement threshold, the user is stationary. */
    if (mag_std < MOTION_STD_THRESHOLD_MAG && sum_std < MOTION_STD_THRESHOLD_AXES) {
        if (out_confidence) {
            float conf_ratio = 1.0f - (mag_std / MOTION_STD_THRESHOLD_MAG);
            if (conf_ratio < 0.6f) conf_ratio = 0.6f;
            if (conf_ratio > 1.0f) conf_ratio = 1.0f;
            *out_confidence = (uint8_t)(conf_ratio * 100.0f);
        }
        return ACTIVITY_STATIONARY;
    }

    int votes_running = 0;
    
    votes_running += tinyml_activity_tree_0(features, ACTIVITY_NUM_FEATURES);
    votes_running += tinyml_activity_tree_1(features, ACTIVITY_NUM_FEATURES);
    votes_running += tinyml_activity_tree_2(features, ACTIVITY_NUM_FEATURES);
    votes_running += tinyml_activity_tree_3(features, ACTIVITY_NUM_FEATURES);
    votes_running += tinyml_activity_tree_4(features, ACTIVITY_NUM_FEATURES);
    votes_running += tinyml_activity_tree_5(features, ACTIVITY_NUM_FEATURES);
    votes_running += tinyml_activity_tree_6(features, ACTIVITY_NUM_FEATURES);
    votes_running += tinyml_activity_tree_7(features, ACTIVITY_NUM_FEATURES);
    votes_running += tinyml_activity_tree_8(features, ACTIVITY_NUM_FEATURES);
    votes_running += tinyml_activity_tree_9(features, ACTIVITY_NUM_FEATURES);
    
    if (votes_running >= 5) {
        if (out_confidence) {
            *out_confidence = (uint8_t)((votes_running * 100) / ACTIVITY_NUM_TREES);
        }
        return ACTIVITY_RUNNING;
    } else {
        if (out_confidence) {
            *out_confidence = (uint8_t)(((ACTIVITY_NUM_TREES - votes_running) * 100) / ACTIVITY_NUM_TREES);
        }
        return ACTIVITY_WALKING;
    }
}

#ifdef __cplusplus
}
#endif

#endif /* TINYML_ACTIVITY_MODEL_H */
