#!/usr/bin/env python3
"""
gen_embedded_songs.py
Generates include/karaoke_embedded_songs.h: the MIDI files compiled into the
firmware as the fallback catalog when no SD card index is available.

The order here is the order of ROM_SONGS[] in src/karaoke_catalog.c. To add a
built-in song, append its song code to EMBEDDED_CODES, add the matching entry to
ROM_SONGS[] and re-run this script.
"""

import argparse
import json
import os

EMBEDDED_CODES = [2106, 36527, 27720]

def c_array(name, data):
    lines = [f'static const uint8_t {name}[] = {{']
    for i in range(0, len(data), 16):
        lines.append('    ' + ', '.join(f'0x{b:02X}' for b in data[i:i + 16]) + ',')
    lines.append('};')
    lines.append(f'static const uint32_t {name}_len = {len(data)};')
    return '\n'.join(lines)

def main():
    parser = argparse.ArgumentParser(description="Generate the built-in karaoke songs header")
    parser.add_argument("--json", default="D:/idx/shub_extracted/shub-songs.json")
    parser.add_argument("--midi", default="D:/idx/shub_extracted/midi")
    parser.add_argument("--out", default=os.path.join(os.path.dirname(__file__), "..", "include", "karaoke_embedded_songs.h"))
    args = parser.parse_args()

    with open(args.json, encoding='utf-8') as f:
        by_code = {int(s['code']): s for s in json.load(f)}

    blocks = []
    for n, code in enumerate(EMBEDDED_CODES, start=1):
        song = by_code[code]
        with open(os.path.join(args.midi, song['file']), 'rb') as f:
            data = f.read()
        if data[:4] != b'MThd':
            raise SystemExit(f"{song['file']} is not a Standard MIDI file")
        print(f"  {n}. {code:06d} {song['singer']} - {song['title']}: {len(data):,} bytes")
        blocks.append(f"/* {code:06d} - {song['singer']} - {song['title']} */\n"
                      + c_array(f'EMBEDDED_MIDI_SONG_{n}', data))

    header = ('/**\n'
              ' * @file karaoke_embedded_songs.h\n'
              ' * @brief ROM fallback karaoke tracks for standalone use without an SD card.\n'
              ' *        Generated by tools/gen_embedded_songs.py; do not edit by hand.\n'
              ' */\n'
              '#ifndef KARAOKE_EMBEDDED_SONGS_H_\n'
              '#define KARAOKE_EMBEDDED_SONGS_H_\n\n'
              '#include <stdint.h>\n\n'
              + '\n\n'.join(blocks)
              + '\n\n#endif /* KARAOKE_EMBEDDED_SONGS_H_ */\n')

    with open(args.out, 'w', newline='\n') as f:
        f.write(header)
    print(f"Wrote {os.path.normpath(args.out)} ({len(header) / 1024:.0f} KB of source)")

if __name__ == '__main__':
    main()
