#!/usr/bin/env python3
"""
gen_opl3_waves.py
Generates the 8 authentic Yamaha OPL3 / TX81Z waveform tables (1,024 samples each,
16-bit signed, totaling 16 KB) directly as const int16_t arrays in Flash memory
in include/opl3_wave_tables.h.
"""

import math
import os

SINE_SIZE = 1024

def gen_tables():
    waves = []
    for wave in range(8):
        arr = []
        for i in range(SINE_SIZE):
            theta = 2.0 * math.pi * float(i) / float(SINE_SIZE)
            s = int(round(math.sin(theta) * 32767.0))
            s2 = int(round(math.sin(2.0 * theta) * 32767.0))
            q = (i * 4) // SINE_SIZE

            if wave == 0:    # WAVE_SINE
                v = s
            elif wave == 1:  # WAVE_HALF
                v = s if q < 2 else 0
            elif wave == 2:  # WAVE_ABS
                v = s if s >= 0 else -s
            elif wave == 3:  # WAVE_QUARTER
                v = s if q == 0 else (-s if q == 2 else 0)
            elif wave == 4:  # WAVE_ALT
                v = s2 if q < 2 else 0
            elif wave == 5:  # WAVE_CAMEL
                v = (s2 if s2 >= 0 else -s2) if q < 2 else 0
            elif wave == 6:  # WAVE_SQUARE
                v = 28000 if q < 2 else -28000
            elif wave == 7:  # WAVE_LOG_SAW
                u = float(i & (SINE_SIZE // 2 - 1)) / float(SINE_SIZE // 2)
                exp_ramp = (1.0 - math.exp(-3.0 * (1.0 - u))) / (1.0 - math.exp(-3.0))
                lsaw = int(round(exp_ramp * 30000.0))
                v = lsaw if q < 2 else -lsaw
            arr.append(max(-32768, min(32767, v)))
        waves.append(arr)
    return waves

def write_header(path):
    waves = gen_tables()
    lines = [
        "/**",
        " * @file opl3_wave_tables.h",
        " * @brief Precomputed 8 Yamaha OPL3 / TX81Z Waveform Tables in Flash ROM (16,384 bytes, 0 B RAM).",
        " *        Generated by tools/gen_opl3_waves.py.",
        " */",
        "",
        "#ifndef OPL3_WAVE_TABLES_H_",
        "#define OPL3_WAVE_TABLES_H_",
        "",
        "#include <stdint.h>",
        "",
        f"#define SINE_BITS      10U",
        f"#define SINE_SIZE      {SINE_SIZE}U",
        f"#define SINE_SHIFT     (32U - SINE_BITS)",
        f"#define NUM_OPL3_WAVES 8U",
        "",
        f"static const int16_t s_waves[NUM_OPL3_WAVES][SINE_SIZE] = {{",
    ]
    for w_idx, arr in enumerate(waves):
        lines.append(f"    /* Waveform {w_idx} */")
        lines.append("    {")
        for i in range(0, len(arr), 16):
            chunk = ", ".join(f"{x:6d}" for x in arr[i:i+16])
            lines.append(f"        {chunk},")
        lines.append("    },")
    lines.append("};\n")
    lines.append("#define s_sine s_waves[0]\n")
    lines.append("#endif /* OPL3_WAVE_TABLES_H_ */\n")

    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"Wrote {path}: 8 waveforms, {len(waves) * SINE_SIZE * 2} bytes in Flash ROM (0 bytes RAM)")

if __name__ == "__main__":
    here = os.path.dirname(os.path.abspath(__file__))
    out = os.path.normpath(os.path.join(here, "..", "include", "opl3_wave_tables.h"))
    write_header(out)
