import os
import csv
import urllib.request
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix
import emlearn

DATASET_URL = "https://raw.githubusercontent.com/ak-cell/run-or-walk-using-ANN/master/runorwalk.csv"
DATASET_FILE = os.path.join(os.path.dirname(__file__), "runorwalk.csv")
MODEL_HEADER = os.path.join(os.path.dirname(__file__), "..", "firmware", "include", "activity_model.h")

def ensure_dataset():
    if not os.path.exists(DATASET_FILE):
        print(f"Downloading Kaggle runorwalk.csv to {DATASET_FILE}...")
        urllib.request.urlretrieve(DATASET_URL, DATASET_FILE)
        print("Download complete.")
    else:
        print(f"Dataset already exists at {DATASET_FILE}")

def load_and_extract_features():
    print("Parsing sensor records and extracting temporal sliding windows...")
    raw_samples = []
    raw_labels = []
    
    with open(DATASET_FILE, 'r', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        for row in reader:
            raw_samples.append([
                float(row['acceleration_x']),
                float(row['acceleration_y']),
                float(row['acceleration_z']),
                float(row['gyro_x']),
                float(row['gyro_y']),
                float(row['gyro_z'])
            ])
            raw_labels.append(int(row['activity']))
            
    X_raw = np.array(raw_samples, dtype=np.float32)
    y_raw = np.array(raw_labels, dtype=np.int32)
    print(f"Loaded {len(X_raw)} raw sensor rows.")
    
    # Sliding window parameters
    # Sampling rate ~5.4 Hz -> 15 samples = ~2.8 seconds
    window_size = 15
    step_size = 7  # 50% overlap
    
    X_win = []
    y_win = []
    
    for i in range(0, len(X_raw) - window_size + 1, step_size):
        win = X_raw[i:i + window_size]
        lbl = y_raw[i:i + window_size]
        
        # Homogeneous activity window
        if np.all(lbl == lbl[0]):
            # 1. Means (6 features)
            means = np.mean(win, axis=0)
            # 2. Standard Deviations (6 features)
            stds = np.std(win, axis=0)
            # 3. Peak-to-peak amplitude range (6 features)
            ranges = np.ptp(win, axis=0)
            # 4. Total acceleration vector magnitude
            acc_mag = np.sqrt(win[:, 0]**2 + win[:, 1]**2 + win[:, 2]**2)
            mag_mean = np.mean(acc_mag)
            mag_std = np.std(acc_mag)
            mag_max = np.max(acc_mag)
            
            features = np.concatenate([
                means,       # 0..5
                stds,        # 6..11
                ranges,      # 12..17
                [mag_mean, mag_std, mag_max]  # 18..20
            ])
            X_win.append(features)
            y_win.append(lbl[0])
            
    X = np.array(X_win, dtype=np.float32)
    y = np.array(y_win, dtype=np.int32)
    print(f"Extracted {len(X)} windows. Features per window: {X.shape[1]}")
    return X, y

def train_and_export():
    ensure_dataset()
    X, y = load_and_extract_features()
    
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42, stratify=y
    )
    
    print("\nTraining compact Random Forest Classifier (10 estimators, max_depth=5)...")
    clf = RandomForestClassifier(n_estimators=10, max_depth=5, random_state=42)
    clf.fit(X_train, y_train)
    
    y_pred = clf.predict(X_test)
    print("\n=== Test Set Performance ===")
    print(classification_report(y_test, y_pred, target_names=["Walking (0)", "Running (1)"], digits=4))
    
    cm = confusion_matrix(y_test, y_pred)
    print("Confusion Matrix:")
    print(f"  Walking: TN={cm[0,0]}, FP={cm[0,1]}")
    print(f"  Running: FN={cm[1,0]}, TP={cm[1,1]}")
    
    print(f"\nGenerating pure C header via emlearn...")
    cmodel = emlearn.convert(clf, method='inline', dtype='float')
    c_code = cmodel.save(name='tinyml_activity')
    
    # Make all generated functions static inline to allow safe header inclusion across translation units
    c_code = c_code.replace("int32_t tinyml_activity_predict(", "static inline int32_t tinyml_activity_predict(")
    c_code = c_code.replace("int tinyml_activity_predict_proba(", "static inline int tinyml_activity_predict_proba(")
    
    # Add wrapper logic for Cortex-M4
    c_header_content = f"""/**
 * ==============================================================================
 * TinyML Activity Classifier Model (Kaggle run-or-walk)
 * Auto-generated by emlearn for ARM Cortex-M4F Hardware FPU
 * ==============================================================================
 * Target: STM32F407ZGT6 (RT-Thread Spark Board)
 * Input: 21 float features extracted from 15-sample (~2.8s) sliding window
 * Output: ACTIVITY_WALKING (0) or ACTIVITY_RUNNING (1)
 * Execution: Pure inline decision trees using single-precision FPU instructions
 * Memory: 0 dynamic allocations (0 malloc bytes)
 */

#ifndef TINYML_ACTIVITY_MODEL_H
#define TINYML_ACTIVITY_MODEL_H

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {{
#endif

#define ACTIVITY_NUM_FEATURES   21
#define ACTIVITY_NUM_TREES      10
#define ACTIVITY_WINDOW_SAMPLES 15

typedef enum {{
    ACTIVITY_WALKING = 0,
    ACTIVITY_RUNNING = 1,
    ACTIVITY_UNKNOWN = 255
}} activity_type_t;

{c_code}

/**
 * @brief Predicts human movement activity from 21 extracted time-domain features.
 * 
 * @param features Pointer to array of 21 float features:
 *                 [0..5]:   Means (ax, ay, az, gx, gy, gz)
 *                 [6..11]:  Std Devs (ax, ay, az, gx, gy, gz)
 *                 [12..17]: Ranges (ax, ay, az, gx, gy, gz)
 *                 [18..20]: Total Accel Magnitude (mean, std, max)
 * @param out_confidence Output pointer for classification confidence (0 to 100 percent)
 * @return activity_type_t ACTIVITY_WALKING or ACTIVITY_RUNNING
 */
static inline activity_type_t tinyml_predict_activity(const float *features, uint8_t *out_confidence)
{{
    int votes_running = 0;
    
    votes_running += tinyml_activity_tree_0(features, ACTIVITY_NUM_FEATURES);
    votes_running += tinyml_activity_tree_1(features, ACTIVITY_NUM_FEATURES);
    votes_running += tinyml_activity_tree_2(features, ACTIVITY_NUM_FEATURES);
    votes_running += tinyml_activity_tree_3(features, ACTIVITY_NUM_FEATURES);
    votes_running += tinyml_activity_tree_4(features, ACTIVITY_NUM_FEATURES);
    votes_running += tinyml_activity_tree_5(features, ACTIVITY_NUM_FEATURES);
    votes_running += tinyml_activity_tree_6(features, ACTIVITY_NUM_FEATURES);
    votes_running += tinyml_activity_tree_7(features, ACTIVITY_NUM_FEATURES);
    votes_running += tinyml_activity_tree_8(features, ACTIVITY_NUM_FEATURES);
    votes_running += tinyml_activity_tree_9(features, ACTIVITY_NUM_FEATURES);
    
    if (votes_running >= 5) {{
        if (out_confidence) {{
            *out_confidence = (uint8_t)((votes_running * 100) / ACTIVITY_NUM_TREES);
        }}
        return ACTIVITY_RUNNING;
    }} else {{
        if (out_confidence) {{
            *out_confidence = (uint8_t)(((ACTIVITY_NUM_TREES - votes_running) * 100) / ACTIVITY_NUM_TREES);
        }}
        return ACTIVITY_WALKING;
    }}
}}

#ifdef __cplusplus
}}
#endif

#endif /* TINYML_ACTIVITY_MODEL_H */
"""
    
    os.makedirs(os.path.dirname(MODEL_HEADER), exist_ok=True)
    with open(MODEL_HEADER, 'w', encoding='utf-8') as f:
        f.write(c_header_content)
        
    print(f"Successfully saved C model header to: {MODEL_HEADER}")
    print(f"Header file size: {os.path.getsize(MODEL_HEADER)} bytes")

if __name__ == '__main__':
    train_and_export()
